[project]
name = "magg"
version = "0.3.0"
description = "MCP Aggregator"
requires-python = ">=3.13"
packages = [{include = "magg"}]
dependencies = [
    "fastmcp<3",
    "aiohttp<4",
    "pydantic<3",
    "pydantic-settings<3",
    "rich>=14.0.0",
]

[project.scripts]
magg = "magg.cli:main"
mbro = "magg.mbro.cli:main"

[project.optional-dependencies]
test = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
]
mbro = [
    "aiocache>=0.12.3",
    "prompt-toolkit>=3.0.51",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "aiocache>=0.12.3",
    "prompt-toolkit>=3.0.51",
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
]
