[project]
name = "limbo"
version = "1.0.0"
requires-python = ">=3.12"
description = "Limbo - MCP Aggregator with Dynamic Tool Loading"
authors = [{ name = "Preetham", email = "preetham@example.com"}]
readme = "readme.md"
license = {text = "AGPL-3.0-or-later"}
license-files = ["license.md"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: Proxy Servers",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
keywords = [
    "model",
    "context",
    "protocol",
    "ai",
    "agent",
    "mcp",
    "aggregator",
    "proxy",
    "limbo",
    "fastmcp",
    "aiohttp",
    "pydantic",
    "pydantic-settings",
    "rich",
]

packages = [
    {include = "limbo"},
    {include = "test", format = "sdist"},
]

include = [
    "readme.md",
    "license.md",
    "compose.yaml",
    "dockerfile",
    ".dockerignore",
    ".env.example",
]

dependencies = [
    "fastmcp>=2.8.0",
    "aiohttp>=3.12.13",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.0",
    "rich>=14.0.0",
    "prompt-toolkit>=3.0.51",
    "cryptography>=45.0.4",
    "pyjwt>=2.10.1",
    "watchdog>=6.0.0",
    "art>=6.5",
]

[project.urls]
Homepage = "https://github.com/Pritz395/limbo"
Repository = "https://github.com/Pritz395/limbo.git"
Documentation = "https://github.com/Pritz395/limbo#readme"
Issues = "https://github.com/Pritz395/limbo/issues"
"Release Notes" = "https://github.com/Pritz395/limbo/releases"

[project.scripts]
limbo = "limbo.cli:main"
mbro = "limbo.mbro.cli:main"

[project.optional-dependencies]
test = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
    "keyring>=25.6.0",
    "anthropic>=0.54.0",
    "pyjwt>=2.10.1",
    "packaging>=25.0",
]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
